name: Hello World
author: Anupam
description: "Greet someone and record the time"
inputs: 
	who_to_greet:
		description: "Who to greet"
		required: true
		default: "World"
outputs: 
	time:
		description: "The time of greeting"
runs: 
	using: "node16" #latest node v compatible to actions
	main: 'dist/index.js' #path of the root file that contains logic
	pre: setup.js #this file runs before running the action
	pre-if: runner.os == 'linux'
	post: cleanup.js #this file runs after running the action
	post-if: runner.os == 'linux'