name: 'Calling Reusable WorkFlow'
on : 
    workflow_dispatch :
jobs : 
    Calling-Reusable-WF-with-output :
        uses : agroot2002/github-action-practice/.github/workflows/reusable-wf-with-output.yaml@main
    Logging-output :
        runs-on : ubuntu-latest
        needs : Calling-Reusable-WF-with-output 
        steps :
            - name : Logging date output from reusable-wf-with-output.yaml
              run : echo '${{ needs.Calling-Reusable-WF-with-output.outputs.date }}'