name: 'Custom message to Issue using js'
on : 
    issues :
        types : [opened]
jobs : 
    Custom-message-to-Issue :
        runs-on : ubuntu-latest
        steps :
            - name : 'step-name'
              uses : actions/github-script@v7
              with : 
                script : |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: '👋 Thanks for reporting the Issue ! \n Soon we will assign someone to look into it .'
                    })
