name: Docker custom script entrypoint
on: [workflow_dispatch]

jobs:
  docker-job:
    runs-on: ubuntu-latest
    container:
      image: node:20.3-alpine3.17
      env:
        API_URL: some-url.com
      ports:
        - 80
    steps:
      - uses: actions/checkout@v3
      - name: Run a bash script
        uses: docker://node:18.16-alpine3.17
        with:
          entrypoint: ./script.sh
          args: "Jai Balaji Jai SiyaRam"