name: Dynamic Environment Variables
on: [push]

env:
  WF_LEVEL_ENV: Available to all jobs

jobs:
    env-vars-and-context:
        runs-on: ubuntu-latest
        # if: $GITHUB_REF == 'refs/heads/main' DONT DO THIS
        if: github.ref == 'refs/heads/main'
        steps :
            - name: Set Env Var
              run: |
                echo "NEW_ENV_VAR=$(date)" >> "$GITHUB_ENV"
                echo "JOB_LEVEL_ENV=$RANDOM" >> "$GITHUB_ENV"

            - name: Multiline ENV Var
              run: |
                DELIMITER=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
                echo "RANDOM_JOKE<<$DELIMITER" >> "$GITHUB_ENV"
                echo "Here is a joke: " >> "$GITHUB_ENV"
                curl -s https://icanhazdadjoke.com/ >> "$GITHUB_ENV"
                echo "" >> "$GITHUB_ENV"
                echo "$DELIMITER" >> "$GITHUB_ENV"

            - name : Log the Env Var
              run : |
                echo $WF_LEVEL_ENV
                echo $JOB_LEVEL_ENV
                echo $NEW_ENV_VAR
                echo $RANDOM_JOKE