# Expected behaiviour : we have set continue-on-error as false this will stop the job once any step fails , fail-fast is set to false to stop other jobs from cancel 

name: 'Matrix Intro'
on : [push]
jobs : 
    Running-Consecutive-Jobs :
        continue-on-error : true
        
        strategy :
            matrix :
                os : [ubuntu-latest , windows-latest]
                node-v : [16,17,18]
                include :
                    - os : macos-latest
                      node-v : 19
                      experimental : true
                exclude :
                    - os : ubuntu-latest
            fail-fast : false

        runs-on : ${{matrix.os}}
        steps :
            - name : 'Node version before '
              run : node -v

            - name : 'Changing Node version'
              uses : actions/setup-node@v3
              with :
                  node-version : ${{matrix.node-v}}

            - name : 'Node version after '
              run : node -v
              
            - name : 'Fail if experimental'
              if : ${{ matrix.experimental }}
              run : exit 1

            - name : 'Matrix log'
              run : echo '${{ toJson(matrix) }}'

# Observations :

# Default Behaviour : as soon as any job fails , other pending jobs got cencelled and the workflow failed

# on Setting continue-on-error to true & fail-fast to false  : as soon as the job failed other job didn't stop and completed , also the workflow succeeded .

# on Setting continue-on-error to false & fail-fast to false  : as soon as the job failed other job didn't stop and completed , but the workflow failed .


# Conclusion : the fail-fast worked as expected , it didn't cancel out other jobs even if any job failed . In case of continue-on-error , it will fail the workflow if set to false and the workflow will show success if this set to true ( in both the cases job will do their work because of fail-fast ) . 