name: Variables and Secrets
on: [push]

jobs:
  log-vars:
    environment : "Production"
    runs-on: ${{ vars.JOB_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
      REPO_VAR: ${{ vars.REPO_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "I ran"
      - name: Log Vars
        run: |
          echo '${{ vars.JOB_RUNNER }}'
          echo "REPO_VAR: $REPO_VAR"
          echo "BOOLEAN_SECRET: $BOOLEAN_SECRET"
          echo "TEST_SECRET: $TEST_SECRET"